#! /usr/bin/env bash

device=$1
community=$2
fs_index=$3

base_fs_table_oid=.1.3.6.1.4.1.23.2.28.2.14.1
totalBlocks_oid=$base_fs_table_oid.3.$fs_index
freeBlocks_oid=$base_fs_table_oid.4.$fs_index

output=`snmpget -v1 -c $community $device $totalBlocks_oid $freeBlocks_oid | awk '{ print $NF; }'`
usedBlocks=`echo $output - p | /usr/bin/dc`
formatted=`echo $output | sed -e 's/ / freeBlocks:/'`
echo "totalBlocks:$formatted usedBlocks:$usedBlocks"
