#! /usr/bin/env bash
#############################################################################
# This program is part of Zenoss Core, an open source monitoring platform.
# Copyright (C) 2007, Zenoss Inc.
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 as published by
# the Free Software Foundation.
#
# For complete information please visit: http://www.zenoss.com/oss/
#############################################################################

. $ZENHOME/bin/zenfunctions

MYPATH=`readlink -f $0`
THISDIR=`dirname $MYPATH`
PRGHOME=`dirname $THISDIR`
PRGNAME=zenperfwbem.py
CFGFILE=$CFGDIR/zenperfwbem.conf
if [ ! -f $CFGFILE ]; then
    touch $CFGFILE
fi

generic "$@"

